<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SJPC" failures="1" tests="3" name="C:/Users/charu/IdeaProjects/org.smartbazaar.com" time="118.949" errors="0" timestamp="2023-03-11T03:14:15 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="23.283">
    <failure type="java.lang.AssertionError" message="expected [https://smartbazaar.co.uk/] but found [https://www.smartbazaar.co.uk/]">
      <![CDATA[java.lang.AssertionError: expected [https://smartbazaar.co.uk/] but found [https://www.smartbazaar.co.uk/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.TestCase.user_verifies_the_title_of_the_application(TestCase.java:25)
at âœ½.User verifies the title of the application(file:///C:/Users/charu/IdeaProjects/org.smartbazaar.com/src/test/resources/Feature/TestCase.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="43.645"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="50.166"/>
</testsuite> <!-- C:/Users/charu/IdeaProjects/org.smartbazaar.com -->
